platform :ios, '15.5.0'

# Include Flutter's helper scripts
require File.expand_path('../.flutter-plugins-dependencies', __FILE__)

# Specify the workspace
workspace 'Runner.xcworkspace'

target 'Runner' do
  use_frameworks!

  # Add all Flutter plugin pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

$iOSVersion = '15.5.0'

post_install do |installer|
  # Update the build configurations for all projects
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new($iOSVersion) > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
      end
    end
  end
end
